spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: provider_api_route
          uri: lb://provider-service
          predicates:
            - Path=/web/**
      discovery:
        locator:
          enabled: true
    consul:
      enabled: true
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        #prefer-ip-address: true
      retry:
        initial-interval: 10
        multiplier: 1
        max-interval: 30000
        max-attempts: 15

reactor:
  netty: debug